import random

# List of cybersecurity facts
cybersecurity_facts = [
    "The most commonly used password is '123456'.",
    "Two-factor authentication (2FA) enhances security by requiring two forms of verification.",
    "A 'firewall' is a network security device that filters incoming and outgoing network traffic.",
    "Phishing is a common cyberattack where attackers trick individuals into revealing sensitive information.",
    "Ransomware is malware that encrypts your data and demands a ransom for decryption.",
    "Ethical hackers, also known as 'white hat' hackers, help organizations by identifying security vulnerabilities.",
    "Regular software updates and patches are essential for maintaining strong cybersecurity.",
    "Social engineering is a tactic that exploits human psychology to gain unauthorized access to systems.",
    "Strong, unique passwords are crucial for account security.",
    "Multi-factor authentication (MFA) provides an extra layer of security by requiring more than one verification method.",
    "A 'virus' is a type of malware that can replicate itself and spread to other files or systems.",
    "A 'worm' is a self-replicating malware that can spread independently.",
    "A 'trojan' or 'trojan horse' is malware that disguises itself as legitimate software to trick users.",
    "Denial-of-Service (DoS) attacks flood a network or service to make it unavailable to users.",
    "Distributed Denial-of-Service (DDoS) attacks involve multiple systems attacking a single target.",
    "A 'botnet' is a network of compromised computers used to perform cyberattacks.",
    "Cybersecurity threats are constantly evolving and require ongoing vigilance.",
    "The 'Dark Web' is a part of the internet that is intentionally hidden and often used for illegal activities.",
    "Data breaches can expose sensitive information like personal, financial, or medical data.",
    "Cryptography is used to protect data by converting it into a secure, unreadable format.",
    "A 'zero-day vulnerability' is a software flaw that is exploited before a fix or patch is available.",
    "Wireless networks can be vulnerable to eavesdropping if not properly secured.",
    "A 'VPN' (Virtual Private Network) can help protect your online privacy by creating a secure, encrypted connection.",
    "Firewalls can block unauthorized network traffic to protect systems and data.",
    "Endpoint security solutions protect individual devices, such as computers and smartphones.",
    "Security policies and awareness training are essential to reduce human errors in cybersecurity.",
    "A 'brute-force attack' is an attempt to crack a password by trying every possible combination.",
    "Security information and event management (SIEM) tools help monitor and respond to security events.",
    "Security audits and penetration testing can identify vulnerabilities in an organization's systems.",
    "The 'Internet of Things' (IoT) refers to the network of interconnected devices and objects.",
    "Public Wi-Fi networks can be insecure, making them vulnerable to cyberattacks.",
    "Encrypting data in transit and at rest helps protect it from unauthorized access.",
    "A 'keylogger' is a type of malware that records keystrokes to capture sensitive information.",
    "Data encryption standards like AES provide strong protection for data.",
    "Cybersecurity certifications, like CISSP and CEH, validate the expertise of professionals.",
    "Cybercriminals use social engineering to manipulate individuals into revealing information or taking specific actions.",
    "Secure Sockets Layer (SSL) and Transport Layer Security (TLS) provide secure communication over the internet.",
    "Data loss prevention (DLP) tools help organizations prevent the accidental or intentional leakage of sensitive data.",
    "'Phishing' emails often impersonate trusted sources to deceive recipients into clicking on malicious links.",
    "'Spear phishing' targets specific individuals or organizations with highly personalized messages.",
    "A 'honeypot' is a cybersecurity decoy designed to lure and monitor cyberattackers.",
    "Mobile devices can be vulnerable to malware and should be protected with security software.",
    "Cybersecurity professionals work to identify and mitigate vulnerabilities to protect systems and data.",
    "A 'security incident' is an event that poses a risk to the confidentiality, integrity, or availability of data.",
    "'Malware' is a general term for various types of malicious software, including viruses, worms, and trojans.",
    "'Adware' is malware that displays unwanted advertisements to the user.",
    "A 'firewall' can be a hardware device or software application that filters network traffic.",
    "Cybersecurity best practices include frequent software updates and patch management.",
    "Data encryption converts information into a code to prevent unauthorized access.",
    "A 'cyberattack' is an intentional and malicious attempt to compromise computer systems, networks, or data.",
    "Sensitive information should be stored securely and accessed only by authorized users.",
    "Security breaches can have legal, financial, and reputational consequences for organizations.",
    "Employees play a crucial role in maintaining strong cybersecurity through awareness and best practices.",
    "A 'honeynet' is a network of honeypots used to detect and study cyberattacks.",
    "'Multi-factor authentication' requires users to provide more than one method of identification.",
    "A 'vulnerability assessment' identifies weaknesses in a system's security controls.",
    "'Penetration testing' (pen testing) involves simulating cyberattacks to test security defenses.",
    "A 'security policy' outlines an organization's approach to protecting data and systems.",
    "Security incidents should be promptly investigated and reported to mitigate potential harm.",
    "The 'CIA triad' stands for Confidentiality, Integrity, and Availability—three critical aspects of information security.",
    "Cryptography techniques, like encryption, are used to secure data and communications.",
    "'Patch management' involves applying updates to address software vulnerabilities.",
    "Regular backups of data help ensure that it can be restored in case of data loss or a ransomware attack.",
    "Cybersecurity professionals may use 'intrusion detection systems' to monitor network traffic for signs of cyberattacks.",
    "Security awareness training helps educate employees about the importance of cybersecurity.",
    "Securing remote work environments is essential to protect against cyber threats.",
    "'Incident response plans' outline the actions to take in the event of a security incident.",
    "Cybersecurity regulations and compliance requirements vary by industry and region.",
    "The 'Zero Trust' security model assumes that threats exist both inside and outside the network.",
    "A 'security audit' assesses an organization's security policies and practices.",
    "A 'security breach' is an unauthorized access or exposure of sensitive data.",
    "Secure coding practices help prevent vulnerabilities in software applications.",
    "'Data exfiltration' refers to the unauthorized transfer of data from a network.",
    "A 'virtual private network' (VPN) provides a secure, encrypted connection over the internet.",
    "Firewalls can block malicious traffic and protect networks from cyber threats.",
    "Cybersecurity incidents can lead to financial losses, legal issues, and reputational damage.",
    "Security awareness training educates employees on recognizing and responding to cybersecurity threats.",
    "'Social engineering' tactics manipulate individuals to divulge confidential information or perform specific actions.",
    "A 'cybersecurity risk assessment' identifies and evaluates potential threats to an organization's

]

# Randomly select and display a cybersecurity fact
random_fact = random.choice(cybersecurity_facts)
print("Cybersecurity fact of the day:")
print(random_fact)